@baseUrl = http://localhost:4000/api/v1

###
# Create Guest
POST {{baseUrl}}/guests
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@email.com",
  "phone": "+639171234567",
  "idType": "National ID",
  "idNumber": "725519999247742"
}

###
# Create Guest But Existing
POST {{baseUrl}}/guests?updateExist=true
Content-Type: application/json

{
  "firstName": "Johnny",
  "lastName": "Sins",
  "email": "john.doe@email.com",
  "phone": "+639171234567",
  "idType": "National ID",
  "idNumber": "725519999247742"
}

###
# Get All Guests
GET {{baseUrl}}/guests

###
# Search Guests
GET {{baseUrl}}/guests?search=johnny

###
# Get Guest By ID
GET {{baseUrl}}/guests/84b23f23a-4e13-4387-90ad-b27f3c9d2471

###
# Update Guest
PUT {{baseUrl}}/guests/4b23f23a-4e13-4387-90ad-b27f3c9d2471
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Wick",
  "phone": "+639189876543",
  "email": "wickjohn@gmail.com"
}
